import { createRequire } from "node:module";
import { execFile, spawn } from "node:child_process";
import { createWriteStream, existsSync } from "node:fs";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, join as join$1 } from "node:path";
import z from "@deepseek-ai/schemastery";
import { installSettingsSection, settingsNamespace } from "@deepseek-ai/dsh-settings";
import { dshHomePath } from "@deepseek-ai/dsh-home-paths";
//#region src/desktop.ts
/**
* DSH Desktop update channel (dshdesktop.cn): the update service that
* distributes this desktop application family. The version endpoint reports
* the latest stable desktop version; the download endpoint 302-redirects to
* the current installer (GitCode / ModelScope CDN). Installation mirrors the
* app's own coordinator: spawn the NSIS installer with --updated --force-run,
* then release the host so the shell quits and the installer takes over.
*/
const UA$1 = "dsh-update-check-plus/0.1.0";
/** Fetch the latest desktop version from the service: {"version":"2.0.0"}. */
async function fetchDesktopVersion(endpoint) {
	const res = await fetch(endpoint, {
		headers: {
			"User-Agent": UA$1,
			Accept: "application/json"
		},
		signal: AbortSignal.timeout(1e4),
		redirect: "error"
	});
	if (!res.ok) return null;
	const body = (await res.text()).slice(0, 4096);
	try {
		const j = JSON.parse(body);
		return typeof j.version === "string" && j.version.length > 0 ? j.version : null;
	} catch {
		return null;
	}
}
/**
* Download the current installer, following the service's redirect chain,
* streaming to disk and reporting progress.
* @returns the local artifact path.
*/
async function downloadInstaller(endpoint, destDir, onProgress) {
	await mkdir(destDir, { recursive: true });
	const res = await fetch(endpoint, {
		headers: { "User-Agent": UA$1 },
		signal: AbortSignal.timeout(18e5),
		redirect: "follow"
	});
	if (!res.ok) throw new Error("installer download HTTP " + res.status);
	const total = Number(res.headers.get("content-length") ?? 0) || 0;
	const disposition = res.headers.get("content-disposition") ?? "";
	const nameMatch = /filename\*?=(?:UTF-8'')?"?([^";]+)"?/i.exec(disposition);
	const fileName = nameMatch !== null ? nameMatch[1].replace(/"/g, "") : "dsh-desktop-setup.exe";
	const dest = join$1(destDir, fileName);
	const tmp = dest + ".tmp";
	const file = createWriteStream(tmp);
	const reader = res.body?.getReader();
	if (reader === void 0) throw new Error("installer response has no body");
	let received = 0;
	let lastReport = 0;
	try {
		for (;;) {
			const { done, value } = await reader.read();
			if (done) break;
			if (value !== void 0) {
				received += value.byteLength;
				file.write(Buffer.from(value));
				if (received - lastReport >= 2097152) {
					lastReport = received;
					onProgress?.({
						received,
						total
					});
				}
			}
		}
	} finally {
		reader.releaseLock();
	}
	await new Promise((resolve, reject) => {
		file.end((err) => err !== void 0 && err !== null ? reject(err) : resolve());
	});
	await rename(tmp, dest);
	onProgress?.({
		received,
		total
	});
	return dest;
}
/**
* Launch the NSIS installer the way the app's own update coordinator does,
* then release this host process so the shell quits and the installer can
* replace the running files.
*/
function launchInstallerAndExit(installerPath, hostExitDelayMs = 3e3) {
	spawn(installerPath, ["--updated", "--force-run"], {
		detached: true,
		stdio: "ignore",
		shell: false,
		windowsHide: false
	}).unref();
	setTimeout(() => {
		try {
			process.exit(0);
		} catch {}
	}, hostExitDelayMs);
}
//#endregion
//#region src/upgradeScript.ts
/**
* One-click engine upgrade support: generates the PowerShell upgrade script
* and launches it detached so it survives this host process being killed.
*/
/** Quote a path for PowerShell single-quoted strings. */
function psq(s) {
	return "'" + s.replace(/'/g, "''") + "'";
}
/**
* Generate the fully automatic engine-upgrade script: kill the app, back up
* the current engine, swap in the staging engine, verify, relaunch; on any
* verification failure it restores the backup and starts the app again.
*/
function buildUpgradeScript(appDir, stagingDir, expectedVersion) {
	join(appDir, "resources", "host");
	join(appDir, "DeepSeek Harness.exe");
	const backupDir = join(stagingDir, "backup-engine");
	const logFile = join(stagingDir, "upgrade.log");
	const L = [];
	L.push("# auto-generated by dsh-update-check-plus: one-click engine upgrade");
	L.push("Start-Sleep -Seconds 4");
	L.push("$ErrorActionPreference = 'Continue'");
	L.push("$log = " + psq(logFile));
	L.push("function Log($m) { $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'; try { \"$ts $m\" | Out-File -FilePath $log -Append -Encoding utf8 } catch {} }");
	L.push("Log '=== engine upgrade: started ==='");
	L.push("$appDir  = " + psq(appDir));
	L.push("$hostDir = Join-Path $appDir 'resources\\host'");
	L.push("$staging = " + psq(stagingDir));
	L.push("$backup  = " + psq(backupDir));
	L.push("$exe     = Join-Path $appDir 'DeepSeek Harness.exe'");
	L.push("Log 'killing running app ...'");
	L.push("$procs = @(Get-Process -Name 'DeepSeek Harness' -ErrorAction SilentlyContinue)");
	L.push("if ($procs.Count -gt 0) { $procs | Stop-Process -Force; Start-Sleep -Seconds 3 }");
	L.push("if (-not (Test-Path (Join-Path $backup 'node_modules'))) {");
	L.push("  Log 'backing up current engine ...'");
	L.push("  robocopy $hostDir $backup /E /MT:16 /NFL /NDL /NJH /NJS /NP | Out-Null");
	L.push("  if ($LASTEXITCODE -ge 8) { Log 'BACKUP FAILED -> abort, restart app'; Start-Process -FilePath $exe; exit 1 }");
	L.push("  Log 'backup done'");
	L.push("} else { Log 'backup already exists, skipping' }");
	L.push("Log 'removing old node_modules ...'");
	L.push("Remove-Item (Join-Path $hostDir 'node_modules') -Recurse -Force -ErrorAction SilentlyContinue");
	L.push("Log 'copying staging engine ...'");
	L.push("Copy-Item (Join-Path $staging 'node_modules') (Join-Path $hostDir 'node_modules') -Recurse -Force");
	L.push("Copy-Item (Join-Path $staging 'package.json') (Join-Path $hostDir 'package.json') -Force");
	L.push("$v = $null");
	L.push("try { $v = (Get-Content -Raw (Join-Path $hostDir 'node_modules\\@deepseek-ai\\dsh\\package.json') | ConvertFrom-Json).version } catch {}");
	L.push("Log ('engine version after replace: ' + $v)");
	L.push("if ($v -ne " + psq(expectedVersion) + ") {");
	L.push("  Log 'VERIFY FAILED -> auto rollback'");
	L.push("  Remove-Item (Join-Path $hostDir 'node_modules') -Recurse -Force -ErrorAction SilentlyContinue");
	L.push("  Copy-Item (Join-Path $backup 'node_modules') (Join-Path $hostDir 'node_modules') -Recurse -Force");
	L.push("  Copy-Item (Join-Path $backup 'package.json') (Join-Path $hostDir 'package.json') -Force");
	L.push("  Log 'rollback done'");
	L.push("  Start-Process -FilePath $exe");
	L.push("  exit 1");
	L.push("}");
	L.push("Log 'starting app ...'");
	L.push("if (-not (Test-Path -LiteralPath $exe)) { Log 'EXE MISSING before start — aborting'; exit 1 }");
	L.push("Start-Process -FilePath $exe");
	L.push("Unregister-ScheduledTask -TaskName 'dsh-upgrade' -Confirm:$false -ErrorAction SilentlyContinue");
	L.push("Log '=== engine upgrade: completed ==='");
	return L.join("\n");
}
/**
* Launch the upgrade script through the Windows Task Scheduler. The task runs
* under the Task Scheduler service, fully independent of this host process —
* killing the app (a required step of the upgrade) can never take it down.
* Plain spawn() (no detached flag): detached:true is unreliable in
* this sandboxed host.
*/
function launchUpgradeViaTaskScheduler(scriptPath, taskName = "dsh-upgrade") {
	const psCmd = "$ErrorActionPreference='Stop'; try { $a = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument '-NoProfile -ExecutionPolicy Bypass -File " + (scriptPath.includes(" ") ? "\"" + scriptPath + "\"" : scriptPath) + "'; $t = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1); Register-ScheduledTask -TaskName '" + taskName + "' -Action $a -Trigger $t -Force | Out-Null; Start-ScheduledTask -TaskName '" + taskName + "'; Write-Output 'scheduled-ok' } catch { Write-Error $_.Exception.Message; exit 1 }";
	spawn("powershell.exe", [
		"-NoProfile",
		"-NonInteractive",
		"-Command",
		psCmd
	], {
		stdio: "ignore",
		shell: false,
		windowsHide: true
	}).unref();
}
//#endregion
//#region src/version.ts
function parseVersion(raw) {
	const v = raw.trim().replace(/^dsh-/, "");
	const m = /^v?(\d+)\.(\d+)\.(\d+)(?:-rc\.(\d+))?$/i.exec(v);
	if (m === null) return null;
	return {
		major: Number(m[1]),
		minor: Number(m[2]),
		patch: Number(m[3]),
		pre: m[4] !== void 0 ? Number(m[4]) : null
	};
}
/** -1 when a < b, 0 when equal, 1 when a > b. */
function compareVersions(a, b) {
	for (const key of [
		"major",
		"minor",
		"patch"
	]) if (a[key] !== b[key]) return a[key] < b[key] ? -1 : 1;
	const ap = a.pre ?? Number.MAX_SAFE_INTEGER;
	const bp = b.pre ?? Number.MAX_SAFE_INTEGER;
	return ap === bp ? 0 : ap < bp ? -1 : 1;
}
//#endregion
//#region src/github.ts
const UA = "dsh-update-check-plus/0.1.0";
function decodeXml(text) {
	return text.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, "\"").replace(/&#39;/g, "'").replace(/&amp;/g, "&");
}
function stripTags(html) {
	return html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
}
function parseAtom(xml) {
	const entries = [];
	const entryRe = /<entry>([\s\S]*?)<\/entry>/g;
	let m;
	while ((m = entryRe.exec(xml)) !== null) {
		const block = m[1];
		const grab = (name) => {
			const mm = new RegExp("<" + name + "(?:[^>]*)?>([sS]*?)</" + name + ">").exec(block);
			return mm !== null ? decodeXml(mm[1].trim()) : "";
		};
		const linkRe = /<link[^>]*href="([^"]+)"/.exec(block);
		entries.push({
			title: grab("title"),
			updated: grab("updated"),
			link: linkRe !== null ? decodeXml(linkRe[1]) : "",
			summary: grab("summary")
		});
	}
	return entries;
}
async function fetchFromApi(repo, limit) {
	const url = "https://api.github.com/repos/" + repo + "/releases?per_page=" + limit;
	const res = await fetch(url, {
		headers: {
			"User-Agent": UA,
			Accept: "application/vnd.github+json"
		},
		signal: AbortSignal.timeout(8e3)
	});
	if (!res.ok) throw new Error("GitHub API HTTP " + res.status);
	return (await res.json()).map((r) => ({
		tag: r.tag_name ?? "",
		name: r.name ?? "",
		publishedAt: r.published_at ?? null,
		prerelease: Boolean(r.prerelease),
		body: r.body ?? "",
		htmlUrl: r.html_url ?? "https://github.com/" + repo + "/releases",
		source: "api"
	})).filter((r) => r.tag.length > 0);
}
async function fetchFromAtom(repo, limit) {
	const feedUrl = "https://github.com/" + repo + "/releases.atom";
	const feedRes = await fetch(feedUrl, {
		headers: { "User-Agent": UA },
		signal: AbortSignal.timeout(5e3)
	});
	if (!feedRes.ok) throw new Error("atom HTTP " + feedRes.status);
	const releases = parseAtom(await feedRes.text()).slice(0, limit).map((entry) => ({
		tag: entry.title,
		name: entry.title,
		publishedAt: entry.updated.length > 0 ? entry.updated : null,
		prerelease: /-rc\./i.test(entry.title),
		body: stripTags(entry.summary),
		htmlUrl: entry.link.length > 0 ? entry.link : "https://github.com/" + repo + "/releases",
		source: "atom"
	}));
	if (releases.length === 0) throw new Error("atom: no entries");
	return releases.filter((r) => r.tag.length > 0);
}
/** Last-resort signal: the version on the default branch, read via raw. */
async function fetchFromMaster(repo) {
	const url = "https://raw.githubusercontent.com/" + repo + "/master/apps/web/package.json";
	const res = await fetch(url, {
		headers: { "User-Agent": UA },
		signal: AbortSignal.timeout(8e3)
	});
	if (!res.ok) throw new Error("raw HTTP " + res.status);
	const version = (await res.json()).version;
	if (version === void 0 || version.length === 0) throw new Error("raw: no version");
	return {
		tag: version,
		name: "master 分支最新版本",
		publishedAt: null,
		prerelease: true,
		body: "GitHub API 配额受限，本次检查来自 master 分支的版本号（apps/web/package.json）。",
		htmlUrl: "https://github.com/" + repo + "/releases",
		source: "master"
	};
}
/**
* Fetch the newest releases. Tries API, then atom, then master-version.
* Never throws when at least the master fallback produced a signal.
*/
async function fetchReleases(repo, limit = 5) {
	try {
		return await fetchFromApi(repo, limit);
	} catch {}
	try {
		return await Promise.any([fetchFromAtom(repo, limit), fetchFromMaster(repo).then((r) => [r])]);
	} catch {
		return [await fetchFromMaster(repo)];
	}
}
async function downloadZipball(repo, tag, dest) {
	const url = "https://codeload.github.com/" + repo + "/zip/refs/tags/" + encodeURIComponent(tag);
	const res = await fetch(url, {
		headers: { "User-Agent": UA },
		signal: AbortSignal.timeout(3e5),
		redirect: "follow"
	});
	if (!res.ok) throw new Error("codeload HTTP " + res.status);
	const buf = Buffer.from(await res.arrayBuffer());
	const tmp = dest + ".tmp";
	await writeFile(tmp, buf);
	await rename(tmp, dest);
	return buf.length;
}
//#endregion
//#region src/state.ts
function emptyState() {
	return {
		currentVersion: null,
		latestTag: null,
		latestName: null,
		latestPublishedAt: null,
		latestBody: null,
		latestUrl: null,
		updateAvailable: false,
		lastCheckedAt: null,
		lastCheckOk: false,
		lastError: null,
		downloads: [],
		desktopVersion: null,
		desktopUpdateAvailable: false,
		desktopLastCheckedAt: null,
		desktopError: null,
		desktopDownload: {
			version: null,
			status: "idle",
			received: 0,
			total: 0,
			path: null,
			error: null
		}
	};
}
async function loadState(path) {
	try {
		const raw = await readFile(path, "utf8");
		const parsed = JSON.parse(raw);
		return {
			...emptyState(),
			...parsed,
			downloads: parsed.downloads ?? []
		};
	} catch {
		return emptyState();
	}
}
async function saveState(path, state) {
	await mkdir(dirname(path), { recursive: true });
	const body = JSON.stringify(state, null, 2);
	for (let attempt = 0; attempt < 3; attempt += 1) try {
		await writeFile(path, body, "utf8");
		return;
	} catch (err) {
		if (attempt === 2) throw err;
		await new Promise((resolve) => setTimeout(resolve, 150 * (attempt + 1)));
	}
}
//#endregion
//#region src/index.ts
/**
* Host half of dsh-update-check-plus: detects the installed app version, polls
* GitHub for the newest deepseek-harness release, persists one state file
* under the DSH home, exposes it over the webServer route, and can
* auto-download the latest source zipball. Everything stays local.
*
* @module dsh-update-check-plus
*/
/** Cordis plugin name (also the row id in cordis.yml). */
const name = "update-check-plus";
/** No hard dependencies: settings/webserver registrations are optional children. */
const inject = [];
const NS = settingsNamespace("update-check-plus");
const Config = z.object({
	repo: z.string().default("deepseek-ai/deepseek-harness"),
	intervalHours: z.number().min(1).default(12),
	autoDownload: z.boolean().default(false),
	downloadDir: z.string().default(""),
	engineStagingDir: z.string().default(""),
	desktopRepoPath: z.string().default(""),
	enableDesktopUpdate: z.boolean().default(false),
	desktopVersionEndpoint: z.string().default("https://www.dshdesktop.cn/api/desktop/version"),
	desktopDownloadEndpoint: z.string().default("https://www.dshdesktop.cn/api/downloads/windows")
});
function detectFromExecutable() {
	return new Promise((resolve) => {
		if (process.platform !== "win32") {
			resolve(null);
			return;
		}
		const cmd = `(Get-Item -LiteralPath '${process.execPath.replace(/'/g, "''")}').VersionInfo.FileVersion`;
		execFile("powershell.exe", [
			"-NoProfile",
			"-NonInteractive",
			"-Command",
			cmd
		], {
			timeout: 1e4,
			windowsHide: true,
			encoding: "utf8"
		}, (err, stdout) => {
			if (err !== null) {
				resolve(null);
				return;
			}
			const line = stdout.trim().split(/\r?\n/)[0]?.trim();
			resolve(line !== void 0 && parseVersion(line) !== null ? line : null);
		});
	});
}
const require = createRequire(import.meta.url);
async function detectCurrentVersion(cfg) {
	try {
		const pkg = require("@deepseek-ai/dsh/package.json");
		if (pkg.version !== void 0 && pkg.version.length > 0 && parseVersion(pkg.version) !== null) return pkg.version;
	} catch {}
	try {
		const hostPkg = join(dirname(process.execPath), "resources", "host", "node_modules", "@deepseek-ai", "dsh", "package.json");
		const j = JSON.parse(await readFile(hostPkg, "utf8"));
		if (j.version !== void 0 && j.version.length > 0 && parseVersion(j.version) !== null) return j.version;
	} catch {}
	try {
		const v = await detectFromExecutable();
		if (v !== null) return v;
	} catch {}
	if (cfg.desktopRepoPath.length > 0) try {
		const raw = await readFile(join(cfg.desktopRepoPath, "upstream.json"), "utf8");
		const j = JSON.parse(raw);
		if (j.sourceVersion !== void 0) return j.sourceVersion;
	} catch {}
	return null;
}
/**
* Run `npm install` in a directory and resolve when the dependency tree is ready.
*/
function runNpmInstall(cwd) {
	return new Promise((resolve, reject) => {
		const cmd = process.platform === "win32" ? "npm.cmd" : "npm";
		execFile(cmd, [
			"install",
			"--no-audit",
			"--no-fund",
			"--loglevel=error"
		], {
			cwd,
			windowsHide: true,
			shell: true,
			timeout: 6e5,
			maxBuffer: 16777216
		}, (error, _stdout, stderr) => {
			if (error !== null) reject(/* @__PURE__ */ new Error(`npm install failed: ${error.message}${stderr.length > 0 ? "\n" + stderr : ""}`));
			else resolve();
		});
	});
}
/**
* Read the running desktop host's dependency-only deploy root package.json.
*/
async function readHostPackage() {
	const hostPkgPath = join(dirname(process.execPath), "resources", "host", "package.json");
	const raw = await readFile(hostPkgPath, "utf8");
	const pkg = JSON.parse(raw);
	if (pkg.version === void 0 || pkg.dependencies === void 0) throw new Error("host package.json is missing version or dependencies");
	return {
		version: pkg.version,
		description: pkg.description,
		dependencies: pkg.dependencies
	};
}
/**
* Make sure the staging engine directory contains a deploy-ready engine of
* exactly `targetVersion`. If it does, returns immediately; otherwise it
* regenerates the dependency-only host from the running app's package.json,
* runs `npm install`, verifies the result, and swaps it into the staging dir.
*/
async function ensureStagingEngine(cfg, targetVersion) {
	const stagingDir = (cfg.engineStagingDir ?? "").length > 0 ? cfg.engineStagingDir : dshHomePath("update-check-plus", "engine");
	const stagedPkgPath = join(stagingDir, "node_modules", "@deepseek-ai", "dsh", "package.json");
	try {
		if (JSON.parse(await readFile(stagedPkgPath, "utf8")).version === targetVersion) return;
	} catch {}
	const preparingDir = stagingDir + ".preparing";
	await rm(preparingDir, {
		recursive: true,
		force: true
	});
	await mkdir(preparingDir, { recursive: true });
	const hostPkg = await readHostPackage();
	const deps = {};
	for (const [name, range] of Object.entries(hostPkg.dependencies)) deps[name] = name.startsWith("@deepseek-ai/dsh") && range.startsWith("^0.1.") ? "^" + targetVersion : range;
	const prepared = {
		name: "@deepseek-ai/dsh-desktop-runtime",
		description: `Dependency-only deploy root for the packaged desktop Host (upgraded to ${targetVersion})`,
		version: targetVersion,
		private: true,
		type: "module",
		dependencies: deps
	};
	await writeFile(join(preparingDir, "package.json"), JSON.stringify(prepared, null, 2), "utf8");
	await runNpmInstall(preparingDir);
	const installedPkgPath = join(preparingDir, "node_modules", "@deepseek-ai", "dsh", "package.json");
	const installed = JSON.parse(await readFile(installedPkgPath, "utf8"));
	if (installed.version !== targetVersion) throw new Error(`staging engine install produced ${installed.version ?? "unknown"}, expected ${targetVersion}`);
	const oldDir = stagingDir + ".old";
	await rm(oldDir, {
		recursive: true,
		force: true
	});
	if (existsSync(stagingDir)) await rename(stagingDir, oldDir);
	await rename(preparingDir, stagingDir);
	await rm(oldDir, {
		recursive: true,
		force: true
	});
}
function serveJson(res, data, status = 200) {
	const body = JSON.stringify(data);
	res.statusCode = status;
	res.setHeader("Content-Type", "application/json; charset=utf-8");
	res.setHeader("Cache-Control", "no-store");
	res.setHeader("Access-Control-Allow-Origin", "*");
	res.end(body);
}
function readBody(req) {
	return new Promise((resolve, reject) => {
		let data = "";
		req.on("data", (chunk) => {
			data += chunk.toString("utf8");
		});
		req.on("end", () => resolve(data));
		req.on("error", reject);
	});
}
/**
* Compose the update-check-plus host capabilities for one plugin fiber.
* @param ctx - Cordis context owning every effect below.
* @param config - composition entry config (possibly partial).
*/
function apply(ctx, config = {}) {
	const base = {
		repo: config.repo ?? "deepseek-ai/deepseek-harness",
		intervalHours: config.intervalHours ?? 12,
		autoDownload: config.autoDownload ?? false,
		downloadDir: config.downloadDir ?? dshHomePath("update-check-plus", "downloads"),
		engineStagingDir: config.engineStagingDir ?? dshHomePath("update-check-plus", "engine"),
		desktopRepoPath: config.desktopRepoPath ?? "",
		enableDesktopUpdate: config.enableDesktopUpdate ?? false,
		desktopVersionEndpoint: config.desktopVersionEndpoint ?? "https://www.dshdesktop.cn/api/desktop/version",
		desktopDownloadEndpoint: config.desktopDownloadEndpoint ?? "https://www.dshdesktop.cn/api/downloads/windows"
	};
	let current = () => base;
	installSettingsSection(ctx, NS, Config, base, {
		setSource: (source) => {
			current = source;
		},
		onChange: () => {}
	});
	const logger = ctx.logger("update-check-plus");
	const statePath = dshHomePath("update-check-plus", "state.json");
	let state = emptyState();
	let versionPromise = null;
	const resolveCurrentVersion = () => {
		versionPromise ??= detectCurrentVersion(current());
		return versionPromise;
	};
	const downloadLatest = async (cfg, tag) => {
		const dir = (cfg.downloadDir ?? "").length > 0 ? cfg.downloadDir : dshHomePath("update-check-plus", "downloads");
		await mkdir(dir, { recursive: true });
		const dest = join(dir, tag + ".zip");
		if (existsSync(dest)) return dest;
		const bytes = await downloadZipball(cfg.repo, tag, dest);
		state = {
			...state,
			downloads: [...state.downloads, {
				tag,
				path: dest,
				bytes,
				at: (/* @__PURE__ */ new Date()).toISOString()
			}].slice(-10)
		};
		await saveState(statePath, state);
		logger.info(`downloaded ${tag} -> ${dest} (${bytes} bytes)`);
		return dest;
	};
	let retryTimer = null;
	const scheduleRetry = () => {
		if (retryTimer !== null) return;
		retryTimer = setTimeout(() => {
			retryTimer = null;
			check();
		}, 36e5);
	};
	let desktopFlowRunning = false;
	let upgradeRunning = false;
	const desktopUpdateFlow = async (cfg) => {
		if (desktopFlowRunning) return;
		desktopFlowRunning = true;
		try {
			const target = state.desktopVersion;
			if (target === null) throw new Error("desktop version unknown; run a check first");
			state = {
				...state,
				desktopDownload: {
					version: target,
					status: "downloading",
					received: 0,
					total: 0,
					path: null,
					error: null
				}
			};
			await saveState(statePath, state);
			const destDir = (cfg.downloadDir ?? "").length > 0 ? cfg.downloadDir : dshHomePath("update-check-plus", "downloads");
			const installerPath = await downloadInstaller(cfg.desktopDownloadEndpoint, destDir, (progress) => {
				state = {
					...state,
					desktopDownload: {
						...state.desktopDownload,
						status: "downloading",
						received: progress.received,
						total: progress.total
					}
				};
				saveState(statePath, state);
			});
			state = {
				...state,
				desktopDownload: {
					...state.desktopDownload,
					status: "downloaded",
					received: 0,
					total: 0,
					path: installerPath
				}
			};
			await saveState(statePath, state);
			logger.info(`desktop update installer ready: ${installerPath}`);
			state = {
				...state,
				desktopDownload: {
					...state.desktopDownload,
					status: "installing"
				}
			};
			await saveState(statePath, state);
			launchInstallerAndExit(installerPath);
		} catch (err) {
			state = {
				...state,
				desktopDownload: {
					...state.desktopDownload,
					status: "error",
					error: err instanceof Error ? err.message : String(err)
				}
			};
			await saveState(statePath, state);
			logger.warn(`desktop update flow failed: ${state.desktopDownload.error}`);
			desktopFlowRunning = false;
		}
	};
	const check = async () => {
		try {
			const cfg = current();
			const currentVersion = await resolveCurrentVersion();
			const [ghResult] = await Promise.allSettled([(async () => {
				const releases = await fetchReleases(cfg.repo, 5);
				if (releases.length === 0) throw new Error("no releases found");
				const candidates = [];
				for (const release of releases) {
					const parsed = parseVersion(release.tag);
					if (parsed !== null) candidates.push({
						release,
						parsed
					});
				}
				const latest = candidates[0] ?? null;
				let updateAvailable = false;
				if (currentVersion !== null && latest !== null) {
					const cur = parseVersion(currentVersion);
					if (cur !== null) updateAvailable = compareVersions(latest.parsed, cur) > 0;
				}
				state = {
					...state,
					currentVersion,
					latestTag: latest?.release.tag ?? null,
					latestName: latest?.release.name ?? null,
					latestPublishedAt: latest?.release.publishedAt ?? null,
					latestBody: latest !== null ? latest.release.body.slice(0, 2e3) : null,
					latestUrl: latest?.release.htmlUrl ?? null,
					updateAvailable,
					lastCheckedAt: (/* @__PURE__ */ new Date()).toISOString(),
					lastCheckOk: true,
					lastError: null
				};
				await saveState(statePath, state);
			})(), (async () => {
				if (!cfg.enableDesktopUpdate) return;
				try {
					const desktopVersion = await fetchDesktopVersion(cfg.desktopVersionEndpoint);
					let desktopUpdateAvailable = false;
					if (desktopVersion !== null && currentVersion !== null) {
						const cur = parseVersion(currentVersion);
						const latestDesktop = parseVersion(desktopVersion);
						if (cur !== null && latestDesktop !== null) desktopUpdateAvailable = compareVersions(latestDesktop, cur) > 0;
					}
					state = {
						...state,
						desktopVersion,
						desktopUpdateAvailable,
						desktopLastCheckedAt: (/* @__PURE__ */ new Date()).toISOString(),
						desktopError: null
					};
					await saveState(statePath, state);
				} catch (err) {
					state = {
						...state,
						desktopError: err instanceof Error ? err.message : String(err),
						desktopLastCheckedAt: (/* @__PURE__ */ new Date()).toISOString()
					};
					await saveState(statePath, state);
				}
			})()]);
			if (ghResult.status === "rejected") {
				state = {
					...state,
					lastCheckOk: false,
					lastError: ghResult.reason instanceof Error ? ghResult.reason.message : String(ghResult.reason),
					lastCheckedAt: (/* @__PURE__ */ new Date()).toISOString()
				};
				await saveState(statePath, state);
				logger.warn(`check failed: ${state.lastError}`);
				scheduleRetry();
			} else {
				if (state.updateAvailable && cfg.autoDownload && state.latestTag !== null) await downloadLatest(cfg, state.latestTag);
				logger.info(`check ok: current=${currentVersion} latest=${state.latestTag} update=${state.updateAvailable} desktop=${state.desktopVersion} desktopUpdate=${state.desktopUpdateAvailable}`);
			}
		} catch (err) {
			state = {
				...state,
				lastCheckOk: false,
				lastError: err instanceof Error ? err.message : String(err),
				lastCheckedAt: (/* @__PURE__ */ new Date()).toISOString()
			};
			await saveState(statePath, state);
			logger.warn(`check failed: ${state.lastError}`);
			scheduleRetry();
		}
		return state;
	};
	ctx.effect(() => {
		let disposed = false;
		let boot = null;
		let interval = null;
		loadState(statePath).then((s) => {
			if (disposed) return;
			state = s;
			boot = setTimeout(() => {
				check();
			}, 1e3);
			const intervalMs = Math.min(Math.max(1, base.intervalHours) * 36e5, 2147483647);
			interval = setInterval(() => {
				check();
			}, intervalMs);
		});
		return () => {
			disposed = true;
			if (boot !== null) clearTimeout(boot);
			if (interval !== null) clearInterval(interval);
		};
	}, "update-check-plus: scheduler");
	ctx.inject(["webServer"], (webCtx) => {
		webCtx.webServer.register({
			kind: "exact",
			path: "/dsh-update-check-plus/state.json",
			handler: (_req, res) => {
				serveJson(res, state);
			}
		});
		webCtx.webServer.register({
			kind: "exact",
			path: "/dsh-update-check-plus/actions/check",
			handler: async (req, res) => {
				if (req.method !== "POST") {
					res.statusCode = 405;
					res.end();
					return;
				}
				await readBody(req);
				serveJson(res, await check());
			}
		});
		webCtx.webServer.register({
			kind: "exact",
			path: "/dsh-update-check-plus/actions/download",
			handler: async (req, res) => {
				if (req.method !== "POST") {
					res.statusCode = 405;
					res.end();
					return;
				}
				await readBody(req);
				try {
					const cfg = current();
					const tag = state.latestTag;
					serveJson(res, {
						ok: true,
						path: tag !== null ? await downloadLatest(cfg, tag) : null
					});
				} catch (err) {
					serveJson(res, {
						ok: false,
						error: err instanceof Error ? err.message : String(err)
					}, 500);
				}
			}
		});
		webCtx.webServer.register({
			kind: "exact",
			path: "/dsh-update-check-plus/actions/desktop-update",
			handler: async (req, res) => {
				if (req.method !== "POST") {
					res.statusCode = 405;
					res.end();
					return;
				}
				await readBody(req);
				if (state.desktopUpdateAvailable && !desktopFlowRunning) desktopUpdateFlow(current());
				serveJson(res, {
					ok: true,
					started: desktopFlowRunning || state.desktopDownload.status === "installing"
				});
			}
		});
		webCtx.webServer.register({
			kind: "exact",
			path: "/dsh-update-check-plus/actions/upgrade",
			handler: async (req, res) => {
				if (req.method !== "POST") {
					res.statusCode = 405;
					res.end();
					return;
				}
				await readBody(req);
				if (upgradeRunning) {
					serveJson(res, {
						ok: false,
						error: "upgrade already running"
					}, 409);
					return;
				}
				try {
					const cfg = current();
					const want = state.latestTag !== null ? state.latestTag.replace(/^dsh-v/, "") : null;
					if (want === null) throw new Error("no known latest version; run a check first");
					upgradeRunning = true;
					const stagingDir = (cfg.engineStagingDir ?? "").length > 0 ? cfg.engineStagingDir : dshHomePath("update-check-plus", "engine");
					await ensureStagingEngine(cfg, want);
					const enginePkgPath = join(stagingDir, "node_modules", "@deepseek-ai", "dsh", "package.json");
					const stagingVersion = JSON.parse(await readFile(enginePkgPath, "utf8")).version ?? "";
					if (stagingVersion !== want) throw new Error("staging engine is " + stagingVersion + ", expected " + want);
					const appDir = dirname(process.execPath);
					const scriptPath = join(stagingDir, "upgrade.ps1");
					await writeFile(scriptPath, buildUpgradeScript(appDir, stagingDir, stagingVersion), "utf8");
					launchUpgradeViaTaskScheduler(scriptPath);
					logger.info("one-click upgrade launched: " + stagingVersion);
					serveJson(res, {
						ok: true,
						stagingVersion,
						upgrading: true
					});
				} catch (err) {
					upgradeRunning = false;
					serveJson(res, {
						ok: false,
						error: err instanceof Error ? err.message : String(err)
					}, 500);
				}
			}
		});
	});
}
//#endregion
export { Config, apply, inject, name };
