/**
 * One-click engine upgrade support: generates the PowerShell upgrade script
 * and launches it detached so it survives this host process being killed.
 */

import { spawn } from 'node:child_process'
import { join } from 'node:path'

/** Quote a path for PowerShell single-quoted strings. */
function psq(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'"
}

/**
 * Generate the fully automatic engine-upgrade script: kill the app, back up
 * the current engine, swap in the staging engine, verify, relaunch; on any
 * verification failure it restores the backup and starts the app again.
 */
export function buildUpgradeScript(appDir: string, stagingDir: string, expectedVersion: string): string {
  const hostDir = join(appDir, 'resources', 'host')
  const exe = join(appDir, 'DeepSeek Harness.exe')
  const backupDir = join(stagingDir, 'backup-engine')
  const logFile = join(stagingDir, 'upgrade.log')
  const L: string[] = []
  L.push('# auto-generated by dsh-update-check-plus: one-click engine upgrade')
  L.push('Start-Sleep -Seconds 4')
  L.push("$ErrorActionPreference = 'Continue'")
  L.push('$log = ' + psq(logFile))
  L.push("function Log($m) { $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'; try { \"$ts $m\" | Out-File -FilePath $log -Append -Encoding utf8 } catch {} }")
  L.push("Log '=== engine upgrade: started ==='")
  L.push('$appDir  = ' + psq(appDir))
  L.push("$hostDir = Join-Path $appDir 'resources\\host'")
  L.push('$staging = ' + psq(stagingDir))
  L.push('$backup  = ' + psq(backupDir))
  L.push('$exe     = Join-Path $appDir \'DeepSeek Harness.exe\'')
  L.push("Log 'killing running app ...'")
  L.push("$procs = @(Get-Process -Name 'DeepSeek Harness' -ErrorAction SilentlyContinue)")
  L.push('if ($procs.Count -gt 0) { $procs | Stop-Process -Force; Start-Sleep -Seconds 3 }')
  L.push("if (-not (Test-Path (Join-Path $backup 'node_modules'))) {")
  L.push("  Log 'backing up current engine ...'")
  L.push('  robocopy $hostDir $backup /E /MT:16 /NFL /NDL /NJH /NJS /NP | Out-Null')
  L.push("  if ($LASTEXITCODE -ge 8) { Log 'BACKUP FAILED -> abort, restart app'; Start-Process -FilePath $exe; exit 1 }")
  L.push("  Log 'backup done'")
  L.push("} else { Log 'backup already exists, skipping' }")
  L.push("Log 'removing old node_modules ...'")
  L.push("Remove-Item (Join-Path $hostDir 'node_modules') -Recurse -Force -ErrorAction SilentlyContinue")
  L.push("Log 'copying staging engine ...'")
  L.push("Copy-Item (Join-Path $staging 'node_modules') (Join-Path $hostDir 'node_modules') -Recurse -Force")
  L.push("Copy-Item (Join-Path $staging 'package.json') (Join-Path $hostDir 'package.json') -Force")
  L.push('$v = $null')
  L.push("try { $v = (Get-Content -Raw (Join-Path $hostDir 'node_modules\\@deepseek-ai\\dsh\\package.json') | ConvertFrom-Json).version } catch {}")
  L.push("Log ('engine version after replace: ' + $v)")
  L.push('if ($v -ne ' + psq(expectedVersion) + ') {')
  L.push("  Log 'VERIFY FAILED -> auto rollback'")
  L.push("  Remove-Item (Join-Path $hostDir 'node_modules') -Recurse -Force -ErrorAction SilentlyContinue")
  L.push("  Copy-Item (Join-Path $backup 'node_modules') (Join-Path $hostDir 'node_modules') -Recurse -Force")
  L.push("  Copy-Item (Join-Path $backup 'package.json') (Join-Path $hostDir 'package.json') -Force")
  L.push("  Log 'rollback done'")
  L.push('  Start-Process -FilePath $exe')
  L.push('  exit 1')
  L.push('}')
  L.push("Log 'starting app ...'")
  L.push("if (-not (Test-Path -LiteralPath $exe)) { Log 'EXE MISSING before start — aborting'; exit 1 }")
  L.push('Start-Process -FilePath $exe')
  L.push("Unregister-ScheduledTask -TaskName 'dsh-upgrade' -Confirm:$false -ErrorAction SilentlyContinue")
  L.push("Log '=== engine upgrade: completed ==='")
  return L.join('\n')
}

/**
 * Launch the upgrade script through the Windows Task Scheduler. The task runs
 * under the Task Scheduler service, fully independent of this host process —
 * killing the app (a required step of the upgrade) can never take it down.
 * Plain spawn() (no detached flag): detached:true is unreliable in
 * this sandboxed host.
 */
export function launchUpgradeViaTaskScheduler(scriptPath: string, taskName = 'dsh-upgrade'): void {
  const argPath = scriptPath.includes(' ') ? '"' + scriptPath + '"' : scriptPath
  const psCmd =
    "$ErrorActionPreference='Stop'; try { " +
    "$a = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument '-NoProfile -ExecutionPolicy Bypass -File " + argPath + "'; " +
    "$t = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1); " +
    "Register-ScheduledTask -TaskName '" + taskName + "' -Action $a -Trigger $t -Force | Out-Null; " +
    "Start-ScheduledTask -TaskName '" + taskName + "'; Write-Output 'scheduled-ok' " +
    "} catch { Write-Error $_.Exception.Message; exit 1 }"
  const child = spawn('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', psCmd], {
    stdio: 'ignore',
    shell: false,
    windowsHide: true,
  })
  child.unref()
}
